### 班级新增
POST http://127.0.0.1:8080/demo/classroom/addClassroom
Accept: application/json
Content-Type: application/json

{
  "name": "四班",
  "year": "2000级",
  "createTime": "",
  "updateTime": "",
  "isDeleted": "0"
}

### 班级修改
POST http://127.0.0.1:8080/demo/classroom/editClassroom
Accept: application/json
Content-Type: application/json

{
  "id": "0004",
  "name": "三班",
  "year": "2017级",
  "createTime": "",
  "updateTime": "",
  "isDeleted": "0"
}

### 班级删除
POST http://127.0.0.1:8080/demo/classroom/removeClassroom
Accept: application/json
Content-Type: application/json

{
  "id": "0004",
  "isDeleted": "1"
}

### 班级查询（1）
POST http://127.0.0.1:8080/demo/classroom/page
Content-Type: application/json
Accept: application/json

{
  "size": 10,
  "current": 1,
  "data": {}
}

### 班级查询（2）
POST http://127.0.0.1:8080/demo/classroom/page
Accept: application/json
Content-Type: application/json

{
  "size": 10,
  "current": 1,
  "data": {
    "name": "一班",
    "year": "2020级"
  }
}

### 班级添加学生
POST http://127.0.0.1:8080/demo/classroom/addClassroomStudent
Accept: application/json
Content-Type: application/json

{
  "id": "0004",
  "students": [
    {
      "id": "101061"
    },
    {
      "id": "101062"
    }
  ]
}
